export const games = [
  { name: "Catan", modes: ["Standard", "Cities & Knights", "Seafarers"] },
  { name: "Scythe", modes: ["Normal", "Automa", "Rise of Fenris"] },
  { name: "Wingspan", modes: ["Base Game", "Solo / Automa", "Asia"] },
  { name: "Root", modes: ["Competitive", "Solo / Clockwork", "Two-player"] },
  { name: "Gloomhaven", modes: ["Campaign", "Jaws of the Lion", "Solo scenario"] },
  { name: "Terraforming Mars", modes: ["Standard", "Solo challenge", "Prelude"] },
  { name: "Ark Nova", modes: ["Standard", "Solo zoo", "Marine Worlds"] },
  { name: "Spirit Island", modes: ["Standard", "Solo spirit", "Adversary"] },
  { name: "Ticket to Ride", modes: ["Classic", "Europe", "1910 expansion"] },
  { name: "Betrayal at House on the Hill", modes: ["Third edition", "Cooperative", "Haunt"] },
  { name: "Dune: Imperium", modes: ["Competitive", "Solo / House Hagal", "Uprising"] },
  { name: "Everdell", modes: ["Standard", "Solo / Rugwort", "Mistwood"] },
  { name: "7 Wonders", modes: ["Classic", "Leaders", "Cities"] },
  { name: "Pandemic", modes: ["Standard", "Heroic", "Solo"] },
  { name: "The Crew", modes: ["Mission deck", "Two-player", "Solo variant"] },
  { name: "Azul", modes: ["Classic", "Summer Pavilion", "Queen's Garden"] },
  { name: "Carcassonne", modes: ["Base game", "Hunters & Gatherers", "Solo"] },
  { name: "Dominion", modes: ["First game", "Random kingdom", "Seaside"] },
  { name: "Mansions of Madness", modes: ["Scenario", "One investigator", "With app"] },
  { name: "Blood on the Clocktower", modes: ["Trouble Brewing", "Sects & Violets", "Custom script"] },
];
